# Generated by Django 3.1.2 on 2021-02-13 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0007_auto_20210212_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='This snippet', max_length=250),
        ),
    ]
